[package]
name = "webshell-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.8", features = ["sqlite"] }
dotenvy = "0.15"
md5 = "0.7.0"
regex = "1.9.1"
hex = "0.4.3"
rusqlite = { version = "0.31", features = ["bundled"] }